### ISSUE TITLE
Two new buttons.

### ISSUE THREAD

**Issue by GlTHUBUSER** [CrazyCat911/Space_Quiz_Webpage#1]
How difficult would it be to introduce 2 new interactive elements? 2 new buttons: "Next" question and "Previous" question at the bottom of the page. Of course "Previous" button would be hidden at the first question and "Next" would be hidden at the last question. "Next" only need to be interactive when current question is answered and answered correctly.

**Comment by CrazyCat911** [comment]
> How difficult would it be to introduce 2 new interactive elements? 2 new buttons: "Next" question and "Previous" question at the bottom of the page. Of course "Previous" button would be hidden at the first question and "Next" would be hidden at the last question. "Next" only need to be interactive when current question is answered and answered correctly.

Should be pretty easy, will do

**Comment by GlTHUBUSER** [comment]
Great, works as intended. Impressive! Thanks for the update.😀
